### ISSUE TITLE
Plugin Configuration issues in Windows 7 64-bit

### ISSUE THREAD

**Issue by LoneStarMac** [jkakavas/creepy#12]
Tried configuring plugins for Instagram, Twitter, and Google+, all three post token errors (below)
```
DEBUG:2015-07-06 15:57:16,420  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-07-06 15:57:16,461  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-07-06 15:57:16,470  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-07-06 15:57:16,483  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
ERROR:2015-07-06 15:57:48,470  In googleplus.py:138: [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\googleplus\\googleplus.conf'
DEBUG:2015-07-06 15:57:50,683  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-07-06 15:57:50,688  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-07-06 15:57:50,694  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-07-06 15:57:50,703  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-07-06 15:58:10,661  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-07-06 15:58:10,667  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-07-06 15:58:10,671  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-07-06 15:58:10,680  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
ERROR:2015-07-06 15:58:46,575  In twitter.py:128: [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\twitter\\twitter.conf'
DEBUG:2015-07-06 15:58:48,885  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-07-06 15:58:48,891  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-07-06 15:58:48,895  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-07-06 15:58:48,904  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
2015-07-06 15:58:51,082 - models.InputPlugin - ERROR - Could not save the configuration for the flickr plugin.
2015-07-06 15:58:51,082 - models.InputPlugin - ERROR - [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\flickr\\flickr.conf'
Traceback (most recent call last):
  File "models\InputPlugin.pyc", line 77, in saveConfiguration
  File "configobj.pyc", line 2128, in write
IOError: [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\flickr\\flickr.conf'
2015-07-06 15:58:51,084 - models.InputPlugin - ERROR - Could not save the configuration for the googleplus plugin.
2015-07-06 15:58:51,084 - models.InputPlugin - ERROR - [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\googleplus\\googleplus.conf'
Traceback (most recent call last):
  File "models\InputPlugin.pyc", line 77, in saveConfiguration
  File "configobj.pyc", line 2128, in write
IOError: [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\googleplus\\googleplus.conf'
2015-07-06 15:58:51,085 - models.InputPlugin - ERROR - Could not save the configuration for the instagram plugin.
2015-07-06 15:58:51,085 - models.InputPlugin - ERROR - [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\instagram\\instagram.conf'
Traceback (most recent call last):
  File "models\InputPlugin.pyc", line 77, in saveConfiguration
  File "configobj.pyc", line 2128, in write
IOError: [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\instagram\\instagram.conf'
2015-07-06 15:58:51,086 - models.InputPlugin - ERROR - Could not save the configuration for the twitter plugin.
2015-07-06 15:58:51,088 - models.InputPlugin - ERROR - [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\twitter\\twitter.conf'
Traceback (most recent call last):
  File "models\InputPlugin.pyc", line 77, in saveConfiguration
  File "configobj.pyc", line 2128, in write
IOError: [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\twitter\\twitter.conf'
```

As you can see, it looks like a bunch of permission errors writing the conf files.

**Comment by jkakavas** [comment]
Hello,

This happens because you have overridden the defaults and installed creepy
in Program Files. Your user does not have permission to write there, so
creepy cant save the configuration.

Please install creepy somewhere you have write permission ( i.e. at your
Home Folder which is the default option ) .

Thanks
Yiannis

2015-07-07 0:00 GMT+03:00 LoneStarMac <notifications@github.com>:

**Comment by LoneStarMac** [comment]
Awesome, I'll do that. The installer detailed to my root drive (c:\creepy)
on install, but I should put it in users/[user]/creepy?

**Comment by jkakavas** [comment]
Hmm that is strange.. If you take a look at the installer for windows at https://github.com/jkakavas/creepy/blob/master/creepy_windows_installer.iss
you can see that the setup directory default is 
```
DefaultDirName={%HOMEPATH}\creepy
```
which according to various resources 
https://windowsforum.com/threads/environment-variables-in-windows-7.48857/
http://environmentvariables.org/HomePath

should point to C:\Users\yourusername


%HOMEDRIVE%\Users\yourusername should be a safe bet for installation

**Comment by LoneStarMac** [comment]
I made a small change to the installer, added a second % to the HOMEPATH env var for Windows. That should work now. Do you want to repackage, or should I build and test on my system first?
