### ISSUE TITLE
pytz not defined

### ISSUE THREAD

**Issue by atekoa** [jkakavas/creepy#21]
Under Win7, cree.py v 1.4.1 
Trying to filter locations by date shows this error and (obviously) no filter is applied:
Traceback (most recent call last):
File "CreepyMain.py", line 254, in showFilterLocationsDateDialog
NameError: global name 'pytz' is not defined

It seems that this "commit" was the one that erased the import.

Autor:		Ioannis Kakavas
Fecha:		hace 4 semanas (18/10/2015 17:51:05)
Hash de Commit:	af33ac8fa66e478da3555e4f1e9b2e1cd184538c
Hijos:		3839b6681a#gitext://gotocommit/3839b6681aecc89c3fcf0db2fa26ad981b92f06a
Padre(s):	5549c5d3ef#gitext://gotocommit/5549c5d3ef1ec6027d0b14b1dbeee365da6d5859

**Comment by jkakavas** [comment]
Hi, 
Thanks for catching this and for providing the information !

**Comment by Taraclia** [comment]
HI! i have the same problem.
  File "CreepyMain.py", line 254, in showFilterLocationsDateDialog
NameError: global name 'pytz' is not defined

**Comment by Taraclia** [comment]
ver. 1.4.1 for windows.

**Comment by DahTse** [comment]
Obviously, this is a known issue.  Is there anything that I can do to help?
