### ISSUE TITLE
execute pyhton CreepyMain.py but nothing happens 

### ISSUE THREAD

**Issue by gtgod1** [jkakavas/creepy#39]
After doing : 
 apt-get remove --purge creepy
  apt-get autoremove
  pip install -U pytz python-qt flickrapi python-instagram yapsy tweepy google-api-python-client python-dateutil configobj dominate

On kali 2.0, i download v 1.41 and after i execute pyhton CreepyMain.py  from the program directory some folders get created but nothing else happens.

**Comment by jkakavas** [comment]
Hi, people have opened a couple of tickets for Kali recently but I havent had the chance to take a look yet. 

When you run 
python CreepyMain.py from your terminal, what is the output ?

**Comment by gtgod1** [comment]
Take your time. I can run v1.3 just fine. It's the new version 1.41 that i can't.
it doesn't even give an output to tell you the truth.

gtgod1@kali:~/jkakavas-creepy-5cb78f7/creepy$ python CreepyMain.py
gtgod1@kali:~/jkakavas-creepy-5cb78f7/creepy$ ls
components  CreepyMain.py  include  models  plugins  ui  utilities
gtgod1@kali:~/jkakavas-creepy-5cb78f7/creepy$ python CreepyMain.py
gtgod1@kali:~/jkakavas-creepy-5cb78f7/creepy$

**Comment by ngharo** [comment]
Debian stretch (Python 2.7.11) has the same behavior.  No output when ran but I did find the log it generates in ~/.creepy

```
$ cat creepy_stderr.log
Traceback (most recent call last):
  File "creepy/CreepyMain.py", line 924, in <module>
    myapp = MainWindow()
  File "creepy/CreepyMain.py", line 137, in __init__
    GeneralUtilities.getProjectsDir()
  File "/home/nick/git/creepy/creepy/utilities/GeneralUtilities.py", line 43, in getProjectsDir
    if e.errno == errno.EEXIST and os.path.isdir(dir):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, builtin_function_or_method found
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
```

**Comment by jkakavas** [comment]
In Kali Linux 2016.1 : 

`apt-get remove --purge creepy`
`git clone https://github.com/jkakavas/creepy.git `

Then go into the creepy folder and run python CreepyMain.py, it should work fine. 

This will have to do until I find time to work with the debian package, sorry for the inconvenience.
