### ISSUE TITLE
Instagram API authentication error

### ISSUE THREAD

**Issue by uptospeed99** [jkakavas/creepy#49]
Error: 
{"code": 403, "error_type": "OAuthForbiddenException", "error_message": "You are not a sandbox user of this client"}

Instagram updated their API terms on June 1st, which places all apps in "Sandbox Mode" until the developers submit their apps for "Live Mode". Developers must fix. Nothing users can do.

https://www.instagram.com/developer/sandbox/

**Comment by jkakavas** [comment]
I'll close all related issues and keep track of the problem here .I just submitted cree.py for validation, I'm not very optimistic that it will fit any of the - rather limited - use cases they allow, but let's see how that goes.

**Comment by jkakavas** [comment]
![creepy_instagram](https://cloud.githubusercontent.com/assets/10281256/18052480/5001f06e-6e03-11e6-9a84-1cf3103efc26.png)

Well, not much I can do here...

**Comment by zaydkhan3** [comment]
so its not able to  be in use temporarily or permanently?

**Comment by jkakavas** [comment]
I would guess permanently ( or until they change their ToS )

**Comment by zaydkhan3** [comment]
Rip the dream dude damn

**Comment by jkakavas** [comment]
A possible way to overcome this restriction is to use cree.py as your own application. In summary :

-  Register your own application with instagram at https://www.instagram.com/developer/clients/manage/
- You can use whatever values you want for name etc.
- Redirect URI value should be http://www.geocreepy.com/get_token.html 
- Get the client id and client secret from your newly created application. 
- Start cree.py and add the client id and client secret in the plugin configuration dialog before you run the wizard. 
- Your app will be sandboxed but you will be able to use it yourself.

**Comment by uptospeed99** [comment]
J: I did attempt as you suggested. First off, in the Run Config Wizard the URL must be updated to https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=code

After obtaining my new Client ID and Client Secret I proceeded to the above URL and was granted a new Token. I then tried the token in Creepy and received the error "Instagram Plugin is not correctly configured. The access_token provided is invalid. Not really sure where to go from here. Thx

**Comment by jkakavas** [comment]
Nope, that is wrong, you don't have to change the URL. The only thing you need to do is to change the client ID and client secret and then save the config with hitting "Apply Configuration" before running the wizard. I updated the instructions above.

**Comment by uptospeed99** [comment]
My apologies J I did get it to work my way, but it also just worked as you described. Now once the wizard states it has been configured correctly I then attempt a username search and rcv the following error:
ERROR:2016-08-30 16:43:47,263  In instagram.py:81: Error searching for targets with instagram plugin.
ERROR:2016-08-30 16:43:47,263  In instagram.py:82: (400) OAuthAccessTokenException-The access_token provided is invalid.

**Comment by uptospeed99** [comment]
Also, I then go back into the configuration settings to test configuration and now it says "Access token invalid" again. Are the access tokens expiring immediately after authorizing?

**Comment by jkakavas** [comment]
No, if you completed the wizard you should have gotten a new access token and access token secret that would be sufficient to perform searches ( as yourself  ) . I will need to take a closer look tomorrow morning, it's already too late.

**Comment by uptospeed99** [comment]
It does seem like the codes are expiring or invalidating almost immediately after being validated via Creepy. It's weird. Anyway I know you have a life and appreciate your responses thus far. :)

**Comment by Exusinst** [comment]
same problem here, I get the Token Value just fine, but when I paste it, it tells me that the access code is invalid

**Comment by MagicMuffins** [comment]
Hello jkakavas, I want to say that this method doesnt work for me. I followed instructions above exactly, but I still get a popup saying that the instagram plugin is not correctly configured. Here is the log output when i try to do this.

ERROR:2016-12-26 11:19:16,301  In instagram.py:209: You must provide a client_id
ERROR:2016-12-26 11:19:16,305  In instagram.py:218: arguments did not match any overloaded call:
  QMessageBox.warning(QWidget, QString, QString, QMessageBox.StandardButtons buttons=QMessageBox.Ok, QMessageBox.StandardButton defaultButton=QMessageBox.NoButton): argument 4 has unexpected type 'NoneType'
  QMessageBox.warning(QWidget, QString, QString, int, int, int button2=0): argument 4 has unexpected type 'NoneType'
  QMessageBox.warning(QWidget, QString, QString, QString, QString button1Text=QString(), QString button2Text=QString(), int defaultButtonNumber=0, int escapeButtonNumber=-1): argument 4 has unexpected type 'NoneType'
Traceback (most recent call last):
  File "CreepyMain.py", line 633, in wizardButtonPressed
    plugin.plugin_object.runConfigWizard()
  File "/home/ground_zero/Desktop/jkakavas-creepy-a861ee3/creepy/plugins/instagram/instagram.py", line 219, in runConfigWizard
    self.showWarning('Error', 'Error was {0}'.format(err))
  File "/home/ground_zero/Desktop/jkakavas-creepy-a861ee3/creepy/plugins/instagram/instagram.py", line 229, in showWarning
    QMessageBox.warning(self.wizard, title, text, None)
TypeError: arguments did not match any overloaded call:
  QMessageBox.warning(QWidget, QString, QString, QMessageBox.StandardButtons buttons=QMessageBox.Ok, QMessageBox.StandardButton defaultButton=QMessageBox.NoButton): argument 4 has unexpected type 'NoneType'
  QMessageBox.warning(QWidget, QString, QString, int, int, int button2=0): argument 4 has unexpected type 'NoneType'
  QMessageBox.warning(QWidget, QString, QString, QString, QString button1Text=QString(), QString button2Text=QString(), int defaultButtonNumber=0, int escapeButtonNumber=-1): argument 4 has unexpected type 'NoneType'

This looks a bit jumbled on my screen, so I will put it neatly in a text file and attatch it. The other plugins work by the way. Also, The first line says that I should provide a client id even though I put in the client id. I will also send a screenshot of the cofiguration as seen.

![screenshot_2016-12-26_11-22-47](https://cloud.githubusercontent.com/assets/20798601/21485798/a98cd1aa-cb5d-11e6-9514-c14df92b03a4.png)
[creepy log output.txt](https://github.com/jkakavas/creepy/files/673266/creepy.log.output.txt)

**Comment by NVolcz** [comment]
Seems like you no longer can access public data from the API, even if you create a app in the sandbox.
I got the access token configuration to work with the following URL:
https://api.instagram.com/oauth/authorize/?client_id=CLIENT_ID&redirect_uri=http://localhost&response_type=token
The token can be tested with the following API:
https://api.instagram.com/v1/users/search?q=jack&access_token=ACCESS-TOKEN

**Comment by jkakavas** [comment]
Thanks @NVolcz , I will take a look !

**Comment by BLCKPSTV** [comment]
I have the same problem, copy with code. Get error. For google plus as for instagram.

**Comment by AxRealGG** [comment]
@jkakavas , how i can get token? please, add axreal_gg to sandboox.

**Comment by spectre57** [comment]
Hello Jkakavas i have a problem with the access token, when i copy my token value from the web browser i get the next message: "Please verify that the link you pasted was correct. Try running the wizard again.

Thanks.

**Comment by Dzianina** [comment]
Anybody interested in this project still here?
I'm struggling with configuring that plugin, I created a project at Insta API, obtained client ID and client secret and when I run configuration wizard I get error:  "You are not a sandbox user of this client".
Can anyone help?
@jkakavas

**Comment by NVolcz** [comment]
@Dzianina The Instagram no longer work due to Instagram restricting the use of their API.

**Comment by uptospeed99** [comment]
Could the developer replace Instagram with VK?
